export const MISSION_NAMES = [
  'Any',
  'Archivum Sycorax',
  'Ascension Riser 31',
  'Chasm Logistratum',
  'Chasm Station HL-16-11',
  'Clandestium Gloriana',
  'Comms-Plex 154/2f',
  'Consignment Yard HL-17-36 ',
  'Dark Communion',
  'Enclavum Baross',
  'Excise Vault Spireside-13',
  'Hab Dreyko',
  'Magistrati Oubliette TM8-707',
  'Mercantile HL-70-04',
  'Power Matrix HL-17-36',
  'Refinery Delta-17',
  'Relay Station TRS-150',
  'Rolling Steel',
  'Silo Cluster 18-66/a',
  'Smelter Complex HL-17-36',
  'Vigil Station Oblivium',
  'Warren 6-19',
];

export const MISSION_TYPES = [
  'Any',
  'Assassination',
  'Disruption',
  'Espionage',
  'Investigation',
  'Operations',
  'Raid',
  'Repair',
  'Strike',
];

export const MISSION_THREATS = [
  'Any',
  'Damnation',
  'Heresy',
  'Malice',
  'Uprising',
  'Sedition',
  // '[Auric] Damnation',
  // '[Auric] Heresy',
  // '[Auric] Malice',
  // '[Auric] Uprising',
  // '[Auric] Sedition',
];

export const MISSION_CONDITIONS = [
  'Any',
  'Hi-Intensity Engagement Zone',
  'Low-Intensity Engagement Zone',
  'Hunting Grounds',
  'Hi-Intensity Hunting Grounds',
  'Low-Intensity Hunting Grounds',
  'Power Supply Interruption',
  'Hi-Intensity Gauntlet (Power Supply Interruption)',
  'Low-Intensity Gauntlet (Power Supply Interruption)',
  'Pox Gas',
  'Hi-intensity Pox Gas',
  'Low intensity Pox Gas',
  'Shock Troop Gauntlet',
  'Hi-Intensity Shock Troop Gauntlet',
  'Low-Intensity Shock Troop Gauntlet',
  'Ventilation Purge',
  'Hi-Intensity Sniper Gauntlet (Ventilation Purge)',
  'Low-Intensity Gauntlet (Ventilation Purge)',
  'Terror in the Dark',
  'Infected Moebian 21st',
  'Mutated Horrors',
  'Brute Conscripts',
];

export const MISSION_BOOKS = [
  'Any',
  'Grimoires',
  'Scriptures',
];

export const MAP_MISSION_TREAT = {
  'Any': 'Any',
  'Damnation': 'threat_5',
  'Heresy': 'threat_4',
  'Malice': 'threat_3',
  'Uprising': 'threat_2',
  'Sedition': 'threat_1',
};
